#!/bin/sh
set -e
# Remove apenas os artefatos gerados; preserva /etc/asterisk-pn/push.env
# (configuracao do usuario) e /etc/asterisk-pn/devices.json (tokens).
echo "[asterisk-pn] removido. /etc/asterisk-pn/push.env e devices.json foram preservados."
exit 0
