#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()
WRITTEN_SECRET=()
SKIPPED=()

_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

say()  { printf '  %s\n' "$1"; }
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=8
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="$REPO_ROOT/.publish.env"

run() {
  printf '  %s$%s %s\n' "$DIM" "$RESET" "$*"
  "$@"
}

banner "Publicar asterisk-pn (Snap Store + Flathub)"

stage "Ferramentas"
say "Precisa do snapcraft para buildar e publicar o snap."
if command -v snapcraft >/dev/null 2>&1; then
  note "snapcraft já instalado."
else
  run sudo snap install snapcraft --classic
fi
if command -v flatpak-builder >/dev/null 2>&1; then
  note "flatpak-builder já instalado (só p/ teste local)."
elif confirm "Instalar flatpak-builder (opcional — só para testar o Flatpak localmente)?"; then
  run sudo apt-get install -y flatpak-builder || true
fi
pause

stage "Autenticação (preflight)"
say "Vou verificar o que já está autenticado antes de começar."
if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
  note "✓ GitHub (gh): autenticado."
else
  warn "GitHub (gh) NÃO autenticado — o Flathub precisa disso."
  step "Rode em outro terminal: gh auth login  (siga o fluxo)."
  pause "Autenticou o gh? Enter para continuar."
fi
if command -v gh >/dev/null 2>&1; then
  _ssh_out="$(timeout 8 ssh -o BatchMode=yes -o StrictHostKeyChecking=accept-new -T git@github.com 2>&1 || true)"
  if [[ "$_ssh_out" == *"successfully authenticated"* ]]; then
    note "✓ SSH para GitHub: ok."
  else
    note "SSH p/ GitHub não confirmado — o push pode usar HTTPS (o gh cuida)."
  fi
fi
if command -v snapcraft >/dev/null 2>&1 && snapcraft whoami >/dev/null 2>&1; then
  note "✓ Snap Store: já logado ($(snapcraft whoami 2>/dev/null))."
else
  note "Snap Store: login será feito na próxima etapa (e-mail + senha + 2FA)."
fi
pause

stage "Snap — login"
say "Logue na sua conta Ubuntu One (Snap Store)."
step "Ele pede e-mail + senha (e 2FA, se ativado)."
run snapcraft login || true
note "Se você já estava logado, este passo só confirma a sessão."
pause

stage "Snap — registrar o nome"
say "Reserva o nome 'asterisk-pn' (já confirmamos que está livre)."
run snapcraft register asterisk-pn || true
pause

stage "Snap — build"
say "Gera o asterisk-pn_<versao>_amd64.snap."
cd "$REPO_ROOT"
if command -v lxd >/dev/null 2>&1 || command -v multipass >/dev/null 2>&1; then
  run snapcraft
else
  warn "Sem lxd/multipass detectado. Usando --destructive-mode (build no host)."
  run snapcraft --destructive-mode
fi
pause

stage "Snap — publicar"
say "Sobe o snap para a Snap Store no canal stable."
run snapcraft upload --release=stable "$REPO_ROOT"/asterisk-pn_*_amd64.snap
note "Depois de publicado: https://snapcraft.io/asterisk-pn"
pause

stage "Flathub — criar o repositório"
say "O Flathub cria um repo para o app; o buildbot dele compila e publica."
open_url "https://flathub.org"
step "Faça login no Flathub (via GitHub)."
step "Clique em 'Submit a new app'."
step "App ID: io.github.wirlleym.asterisk-pn"
step "Escolha 'Build with GitHub' e confirme."
step "O Flathub cria o repo flathub/io.github.wirlleym.asterisk-pn e mostra seu fork."
ask FLATHUB_FORK_URL "Cole a URL do SEU fork (ex.: git@github.com:<voce>/io.github.wirlleym.asterisk-pn.git):"
write_env FLATHUB_FORK_URL "$FLATHUB_FORK_URL"
pause

stage "Flathub — enviar manifest e abrir PR"
say "Envia o manifest + metainfo para o seu fork e abre o PR no Flathub."
if [[ -z "$FLATHUB_FORK_URL" ]]; then
  warn "URL do fork vazia. Re-role o wizard e cole a URL do fork nesta etapa."
  exit 1
fi
FLATHUB_DIR=$(mktemp -d)
run git clone "$FLATHUB_FORK_URL" "$FLATHUB_DIR"
run cp "$REPO_ROOT/packaging/flatpak/io.github.wirlleym.asterisk-pn.yml" "$FLATHUB_DIR/"
run cp "$REPO_ROOT/packaging/flatpak/io.github.wirlleym.asterisk-pn.metainfo.xml" "$FLATHUB_DIR/"
cd "$FLATHUB_DIR"
git checkout -b asterisk-pn 2>/dev/null || true
git add -A
git commit -m "Add io.github.wirlleym.asterisk-pn (asterisk-pn)" || true
run git push -u origin asterisk-pn
if command -v gh >/dev/null 2>&1; then
  run gh pr create --repo flathub/io.github.wirlleym.asterisk-pn \
    --title "Add io.github.wirlleym.asterisk-pn" \
    --body "Manifest do asterisk-pn (asterisk-push-notify)." || true
else
  note "Abra o PR manualmente no GitHub (link que o Flathub mostrou no passo anterior)."
fi
note "Acompanhe o build: https://flathub.org/apps/details/io.github.wirlleym.asterisk-pn"
pause

finish
